### ISSUE TITLE
Don't randomise the order after the back button

### ISSUE THREAD

**Issue by stuartlangridge** [operasoftware/pwa.rocks#106]
If you view pwa.rocks, click one app to try it, then click back to go back to the list, the list's order is randomised. I understand why it's randomised on first visit, and that's great, but if it's randomised on _every_ visit then it's really hard to go through and try out various different PWAs, because you've lost your "place" in the list.

**Comment by pepelsbey** [comment]
Do you think a cookie or sessionStorage entry would solve this problem?

**Comment by stuartlangridge** [comment]
Yeah, that'd likely do it!

**Comment by andreasbovens** [comment]
@pepelsbey shall we close this one?

**Comment by pepelsbey** [comment]
Yep, it's fixed, thank you for suggestion @stuartlangridge
